[package]
name = "ama"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "ama"
path = "src/lib.rs"

[[bin]]
name = "ama"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
proptest.workspace = true
tempfile.workspace = true
